sudo: false
language: python
dist: trusty
python: 3.5

before_install:
    - echo "before_install (Download miniconda)"
    - export PATH="$HOME/miniconda3/bin:$PATH"
    - df -h
    - pwd
    - uname -a
    - git --version
    - git tag

install:
    - echo "install dbcollection"
    - chmod +x ci/travis_install.sh
    - ci/travis_install.sh
    - echo "install done"
    - source activate dbcollection
    - git clone https://github.com/dbcollection/dbcollection && cd dbcollection && python setup.py install

script:
  - echo "test dbcollection"
  - python -c "import dbcollection as dbc; mnist=dbc.load('cifar10'); print(mnist)"
  - echo "test done"
