sudo: false
language: c
os:
  - linux

compiler:
  - gcc
  - clang

cache:
  directories:
  - $HOME/OpenBlasInstall

env:
  - TORCH_LUA_VERSION=LUAJIT21

addons:
  apt:
    packages:
    - cmake
    - gfortran
    - gcc-multilib
    - gfortran-multilib
    - liblapack-dev
    - build-essential
    - gcc
    - g++
    - curl
    - cmake
    - libreadline-dev
    - git-core
    - libqt4-core
    - libqt4-gui
    - libqt4-dev
    - libjpeg-dev
    - libpng-dev
    - ncurses-dev
    - imagemagick
    - libzmq3-dev
    - gfortran
    - unzip
    - gnuplot
    - gnuplot-x11
    - libhdf5-serial-dev
    - hdf5-tools

before_script:
  - echo "install torch"
  - export ROOT_TRAVIS_DIR=$(pwd)
  - export INSTALL_PREFIX=~/torch/install
  -  ls $HOME/OpenBlasInstall/lib || (cd /tmp/ && git clone https://github.com/xianyi/OpenBLAS.git -b master && cd OpenBLAS && (make NO_AFFINITY=1 -j$(getconf _NPROCESSORS_ONLN) 2>/dev/null >/dev/null) && make PREFIX=$HOME/OpenBlasInstall install)
  - git clone https://github.com/torch/distro.git ~/torch --recursive
  - cd ~/torch && git submodule update --init --recursive
  - mkdir build && cd build
  - export CMAKE_LIBRARY_PATH=$HOME/OpenBlasInstall/include:$HOME/OpenBlasInstall/lib:$CMAKE_LIBRARY_PATH
  - cmake .. -DCMAKE_INSTALL_PREFIX="${INSTALL_PREFIX}" -DCMAKE_BUILD_TYPE=Release -DWITH_${TORCH_LUA_VERSION}=ON
  - make && make install
  - cd $ROOT_TRAVIS_DIR
  - export LD_LIBRARY_PATH=${INSTALL_PREFIX}/lib:$LD_LIBRARY_PATH
  - ${INSTALL_PREFIX}/bin/luarocks install torch
  - ${INSTALL_PREFIX}/bin/luarocks install hdf5

install:
  - echo "install dbcollection"
  - pip install dbcollection
  - echo "package installed"

script:
  - echo "install dbcollection-torch7"
  - ${INSTALL_PREFIX}/bin/luarocks make rocks/dbcollection-scm-1.rockspec
  - export PATH=${INSTALL_PREFIX}/bin:$PATH
  - export TESTLUA=$(which luajit lua | head -n 1)
  - ${TESTLUA} -e "dbc = require 'dbcollection'; t=dbc.test(); if t.errors[1] then os.exit(1) end"
