sudo: false
language: python
dist: trusty
python:
    - 3.5

install:
    - echo "install dbcollection"
    - pip install dbcollection
    - echo "install done"

script:
  - echo "test dbcollection"
  - python -c "import dbcollection as dbc; mnist=dbc.load('mnist'); print(mnist)"
  - echo "test done"
